//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDays.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.Mensualidad = new HashSet<Mensualidad>();
            this.Notas = new HashSet<Notas>();
        }
    
        public int Cedula { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Nombre_Papa { get; set; }
        public int Numero_Papa { get; set; }
        public string Nombre_Mama { get; set; }
        public int Numero_Mama { get; set; }
        public int Telefono_Hogar { get; set; }
        public string Correo { get; set; }
        public string CorreoOtro { get; set; }
        public string Otros { get; set; }
        public Nullable<int> ID_Grado { get; set; }
    
        public virtual Grados Grados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensualidad> Mensualidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas> Notas { get; set; }
    }
}
