//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDays.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidad
    {
        public int ID_Mensualidad { get; set; }
        public string Tipo { get; set; }
        public int Monto { get; set; }
        public int ID_Estudiante { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
