//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDays.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDaysEntities2 : DbContext
    {
        public SchoolDaysEntities2()
            : base("name=SchoolDaysEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Grado> Grados { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Mensualidad> Mensualidads { get; set; }
        public virtual DbSet<Nota> Notas { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Salario> Salarios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
