//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDays.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int ID_Nota { get; set; }
        public int PrimerParcial { get; set; }
        public int SegundoParcial { get; set; }
        public int TercerParcial { get; set; }
        public int Tareas { get; set; }
        public int TrabajoCotidiano { get; set; }
        public Nullable<int> ID_Grado { get; set; }
        public Nullable<int> ID_Profesor { get; set; }
        public Nullable<int> ID_Materia { get; set; }
        public Nullable<int> ID_Estudiante { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Grados Grados { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
