//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDays.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Telefono_Hogar { get; set; }
        public int Celular { get; set; }
        public string Correo { get; set; }
        public string DireccionHogar { get; set; }
        public int ID_Materia { get; set; }
        public int ID_Salario { get; set; }
        public int ID_Horario { get; set; }
        public int ID_Grado { get; set; }
    
        public virtual Grados Grados { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Materia Materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas> Notas { get; set; }
        public virtual Salario Salario { get; set; }
    }
}
